# Generated by Django 5.2.12 on 2026-04-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_user_role_election'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='is_manually_controlled',
            field=models.BooleanField(default=False),
        ),
    ]
