# Generated by Django 4.2.23 on 2026-05-15 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_vote'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='myapp.election')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='candidate',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='myapp.post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vote',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.post'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together={('user', 'election', 'post')},
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('voter', 'election', 'post')},
        ),
    ]
