# Generated by Django 4.2.23 on 2026-06-21 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_post_alter_vote_unique_together_candidate_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='ai_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='ai_score',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='ai_theme',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
