# Generated by Django 4.2.23 on 2026-06-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_candidate_date_of_birth_candidate_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='application_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidate',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='manifesto',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('nominated', 'Nominated'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='applied', max_length=20),
        ),
    ]
