# Generated by Django 4.2.23 on 2026-06-26 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_candidate_application_attempts_candidate_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('nominated', 'Nominated'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disqualified', 'Disqualified')], default='applied', max_length=20),
        ),
    ]
